extends RefCounted
class_name PrototypeState

static func create(config: Dictionary, rng: RandomNumberGenerator) -> Dictionary:
	var player_max_hp = float(config.get("playerMaxHP", 100))
	return {
		"elapsed": 0.0,
		"paused": true,
		"selectingItem": false,
		"selectingPerk": false,
		"selectingModule": false,
		"selectingPaidReward": false,
		"gameOver": false,
		"timeScale": 1.0,
		"gold": 0,
		"xp": 0,
		"xpNeed": int(config.get("xpBaseRequirement", 40)),
		"level": 1,
		"heat": 0.0,
		"creditScore": 50,
		"investedGold": 0,
		"debtGold": 0,
		"sponsoredCompletions": 0,
		"sponsoredAttackBoostStacks": 0,
		"nextItemDiscounts": [],
		"nextItemExtraChoices": 0,
		"killCount": 0,
		"itemRollCount": 0,
		"termsPenaltyCount": 0,
		"adOpenTime": 0.0,
		"firstPurchaseOfferShown": false,
		"firstPurchasePaid": false,
		"firstPurchasePackageChosen": "",
		"activePlaystyle": "",
		"activePlaystyleName": "미선택",
		"firstPurchaseTimer": rng.randf_range(3.0, 5.0),
		"lastItemText": "최근 아이템: 없음",
		"recentPerkText": "공격 모듈을 선택하세요.",
		"primaryModule": "",
		"secondaryModule": "",
		"primaryMastery": 0,
		"secondaryMastery": 0,
		"primaryDeepening": {},
		"secondaryDeepening": {},
		"moduleSynergy": {},
		"moduleUpgrades": {
			"primary": {"form": "", "mechanic": "", "scaling": ""},
			"secondary": {"form": "", "mechanic": "", "scaling": ""},
		},
		"moduleCharge": {"primary": 0.0, "secondary": 0.0},
		"moduleTimers": {"primary": 0.25, "secondary": 0.7},
		"lastDifficultyStageId": "normal",
		"difficultyPulseTimer": 0.0,
		"difficultyNoticeText": "",
		"difficultyNoticeTimer": 0.0,
		"waveDirector": {
			"mode": "normal",
			"timer": rng.randf_range(15.0, 25.0),
			"nextModeTimer": rng.randf_range(15.0, 25.0),
			"intensity": 1.0,
			"noticeTimer": 0.0,
			"noticeText": "",
			"side": "left",
			"lastMode": "normal",
			"intenseLast": false,
		},
		"popupExecutionWindow": 0.0,
		"cleanupComboWindow": 0.0,
		"cleanupComboStacks": 0,
		"cleanupComboValue": 0,
		"cleanupComboTimer": 0.0,
		"cleanupComboGrace": 4.0,
		"cleanupComboMax": 20,
		"cleanupComboPulse": 0.0,
		"popupCloseAttackPrimed": false,
		"bossSpawnIndex": 0,
		"bossPackageCount": 0,
		"pendingBossPackage": {},
		"itemCounts": {},
		"timedEffects": [],
		"delayedEvents": [],
		"enemyTimer": 0.8,
		"popupTimer": 12.0,
		"attackTimer": 0.25,
		"emergencyTimer": 0.0,
		"emergencyBoostTimer": 0.0,
		"autoCloseBasicTimer": 8.0,
		"popupFreezeTimer": 0.0,
		"lowHpFreezeUsed": false,
		"adGoldBank": 0.0,
		"metrics": {
			"interestAccepted": 0,
			"interestCompleted": 0,
			"interestLost": 0,
			"popupStorePurchases": 0,
			"passiveGoldEarned": 0,
			"bossKills": 0,
			"bossPackagesPurchased": 0,
			"sponsoredRewards": 0,
			"volatileClosures": 0,
		},
		"stockMarket": {
			"selectedSymbol": "POP",
			"tickTimer": 1.0,
			"lastBiasLabel": "조용한 장세",
			"stock": {
				"symbol": "POP",
				"name": "팝업 테마주",
				"price": 100.0,
				"history": [100.0],
				"volatility": 0.085,
				"drift": 0.003,
				"shares": 0,
				"avgCost": 0.0,
				"lastChange": 0.0,
			},
		},
		"player": {
			"position": Vector2.ZERO,
			"radius": 13.0,
			"hp": player_max_hp,
			"maxHP": player_max_hp,
			"hitFlash": 0.0,
		},
		"camera": {
			"position": Vector2(-float(config.get("canvasWidth", 960)) * 0.5, -float(config.get("canvasHeight", 540)) * 0.5),
		},
		"stats": create_stats(config),
		"enemies": [],
		"mines": [],
		"turrets": [],
		"fields": [],
		"projectiles": [],
		"chargeCasts": [],
		"floatTexts": [],
		"particles": [],
		"screenShake": {"amount": 0.0, "timer": 0.0},
		"residentPrograms": [],
		"residentProgramIdSeed": 1,
		"reservedMaxHP": 0,
		"securityUpdateTimer": rng.randf_range(18.0, 26.0),
		"securityBillingTimer": 0.0,
		"pickups": [],
		"attacks": [],
		"openPopups": [],
		"pendingPopupSpawns": [],
		"pointerScreenX": null,
		"pointerScreenY": null,
		"lastMoveDir": Vector2.RIGHT,
		"mobileInput": {
			"active": false,
			"pointerId": -1,
			"baseX": 0.0,
			"baseY": 0.0,
			"x": 0.0,
			"y": 0.0,
			"fallbackClickButton": null,
			"fallbackClickUntil": 0.0,
			"fallbackTouches": {},
		},
		"draggingPopup": null,
	}

static func create_stats(config: Dictionary) -> Dictionary:
	return {
		"damageMultiplier": 0.0,
		"attackIntervalMultiplier": 0.0,
		"attackRangeMultiplier": 0.0,
		"moveSpeedMultiplier": 0.0,
		"popupDragSpeedMultiplier": 0.0,
		"popupSpawnRateMultiplier": 0.0,
		"adGoldPerSecond": 0.0,
		"adGoldMultiplier": 0.0,
		"adBuffMultiplier": 0.0,
		"sponsoredRewardMultiplier": 0.0,
		"sponsoredPopupWeightMultiplier": 0.0,
		"timedRewardDurationMultiplier": 0.0,
		"maxOpenPopups": int(config.get("maxOpenPopups", 5)),
		"extraTargets": 0,
		"cleanDeskDamageMultiplier": 0.0,
		"clutterAttackIntervalPerPopup": 0.0,
		"goldBulletDamageMultiplier": 0.0,
		"emergencyMoveSpeedMultiplier": 0.0,
		"autoCloseBasicInterval": 0.0,
		"sponsoredDoubleHit": 0,
		"purchaseDamageBurst": 0.0,
		"dragAttackIntervalMultiplier": 0.0,
		"popupCloseDamage": 0.0,
		"delayedMaxHPLoss": 0.0,
		"termsPopupWeightMultiplier": 0.0,
		"goldPerPopupClose": 0,
		"safeZoneMultiplier": 0.0,
		"emergencyCooldownMultiplier": 0.0,
		"termsPenaltyShield": 0,
		"crowdedGoldMultiplier": 0.0,
		"smartEmergencyClose": 0,
		"lowHpPopupFreeze": 0,
		"goldPerTermsPenalty": 0,
		"crowdedItemDiscount": 0.0,
		"emergencyCloseDisabled": 0,
		"rewardGoldMultiplier": 0.0,
		"interestPopupWeightMultiplier": 0.0,
		"interestPayoutMultiplier": 0.0,
		"popupStoreWeightMultiplier": 0.0,
		"popupStoreDiscountMultiplier": 0.0,
		"debtItemCostMultiplier": 0.0,
		"healthRegenPerSecond": 0.0,
		"lifeStealPercent": 0.0,
		"lifeStealFlat": 0.0,
		"healingMultiplier": 0.0,
		"missingHpRegenMultiplier": 0.0,
		"lowHpDamageMultiplier": 0.0,
		"lowHpCooldownMultiplier": 0.0,
		"maxHpDamageMultiplier": 0.0,
		"cleanupComboGraceBonus": 0.0,
		"pickupRangeMultiplier": 0.0,
		"pickupRangeFlat": 0.0,
		"cleanupComboPickupRangeMultiplier": 0.0,
		"critChance": 0.0,
		"critDamageMultiplier": 0.5,
		"critDamagePerDifficulty": 0.0,
	}
